package com.hurix.api.runner;

import io.restassured.response.Response;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import org.apache.http.HttpStatus;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.json.JSONException;
import com.hurix.api.readerAPIs.Authenticate;
import com.hurix.api.readerAPIs.FetchBookList;
import com.hurix.api.readerAPIs.RefreshCategory;
import com.hurix.api.utility.ExcelUtils;
import com.hurix.api.utility.ExtractCategory;
import com.hurix.api.utility.Validation;
import com.hurix.automation.utility.Log;

public class DIS_1838 {

	public static List<String> detailisbn =  ExcelUtils.getisbn();
	DateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
	Date dateobj = new Date();
	//System.out.println(df.format(dateobj));
	//public static long startDate1 = EpochTime.getEpochTime("df.format(dateobj");
	public static long startDate ;//EpochTime.getEpochTime("2019/10/31 14:46:04");
	public static long startIndex = 0;
	public static long endIndex = 100;
	//public static int level;
	public static String assetType;
	public static int level;
	public static String numberOfBooks;
	public static String userToken = "";
	public static int BookID_mark1;
	public static int BookID_mark2;
	public static int BookID_mark3;
	public static int  bookID1;
	public static int bookID2;
	public static int bookID3;
	public static int bookID6;
	public static String isbn;
	public static String isbnMeta;
	public static String isbnIng;
	public static String forName;
	public static String responseMsg;
	public static String content_ownership;
	public static int userID;
	public static int totalbooks;
	public static int total;
	public static String archiveDate;
	public static String archiveDate6;
	public static String operation0;
	public static String operation1;
	public static String ebookID1;
	public static String catname;
	public static String categoriesname;
	public static String collectionName0;
	public static String collectionName1;
	public static String catname1;
	public static int totalCategories;
	public static String clientUserID;
	public static String category1;
	public static String clientBookID;
	public static String search = "Native";	
	public static XSSFWorkbook workbook;
	public static XSSFSheet sheet;
	public static String environMent;
	public static String userName;
	public static String password;
	public static String detail;
	public static String externalURI;
	public static String clientID;
	public static String catlevel;
	public static int type;
	public static String isbn1;
	public static String isbn2;
	public static String isbn3;
	public static String isbn4;
	public static String isbn5;
	public static String isbn6;
	public static String isbn7;
	public static String isbn8;
	public static String isbn9;
	public static String isbn10;
	public static String isbn11;
	public static String consumerKey;
	public static String consumerSecret;
	public static Object categoryIdList0;
	public static Object categoryIdList1;
	public static Object categoryIdList2;
	public static Object categoryIdList3;
	public static Object categoryIdList4;
	public static String category;
	public static Object categoryList;
	public static Object categoryIdList;
	public static String title;
	//public static String consumerKey=ExcelUtils.Consumer_key;
	//public static String consumerSecret=ExcelUtils.secret_key;

	public static void   main(String []args) throws SQLException, JSONException{
		Log.initialization("DIS_1838");	
		//List<String> detail =  ExcelUtils.getuserDetails();
		try {
			//startDate=EpochTime.getEpochTime(""+startDate+"");
			String excelPath="./testData/DIS-1838.xlsx";
			workbook = new XSSFWorkbook(excelPath);
			sheet= workbook.getSheet("Sheet1");
			for(int i=1;i<=1;i++)
			{	
				DataFormatter formatter = new DataFormatter();
				environMent = formatter.formatCellValue(sheet.getRow(i).getCell(0));
				userName=formatter.formatCellValue(sheet.getRow(i).getCell(1));			
				password=formatter.formatCellValue(sheet.getRow(i).getCell(2));
				consumerKey=formatter.formatCellValue(sheet.getRow(i).getCell(4));
				consumerSecret=formatter.formatCellValue(sheet.getRow(i).getCell(5));
				clientID=formatter.formatCellValue(sheet.getRow(i).getCell(3));	
				catlevel=formatter.formatCellValue(sheet.getRow(i).getCell(6));	

				switch(environMent){
				case "QC":
					detail = "http://qc.kitaboo.com";
					break;
				case "Staging":
					detail = "http://qacloud.kitaboo.com";
					break;
				case "BASE_US":
					detail = "http://localhost:12346";
					break;
				case "BASE_EU":
					detail = "http://localhost:12347";
					break;
				case "PROD_US":
					detail = "http://cloud.kitaboo.com";
					break;
				case "PROD_EU":
					detail = "http://cloud.kitaboo.eu";
					break;
				}				
				io.restassured.RestAssured.baseURI = detail;
				System.out.println("detail : "+detail);
				System.out.println("userName : "+userName);
				System.out.println("password : "+password);
				Log.startTestCase("Authenticate");
				Response authenticateValue = Authenticate.authenticate(clientID, userName, password,"514185","IPAD");
				Log.info("Authenticate Response: "+authenticateValue.then().extract().response().prettyPrint());				
				System.out.println("HERE_Before");
				Log.info("clientID : "+clientID);
				Validation.responseHeaderCodeValidation(authenticateValue, HttpStatus.SC_OK);
				Validation.responseCodeValidation1(authenticateValue, HttpStatus.SC_OK);
				Validation.responseTimeValidation(authenticateValue);
				Validation.responseKeyValidation_key(authenticateValue, "userName");
				Validation.responseKeyValidation_key(authenticateValue, userName);
				System.out.println("HERE_After");
				System.out.println("here");
				userName = authenticateValue.then().extract().path("user.userName");
				userID = authenticateValue.then().extract().path("user.id");
				System.out.println("userID: "+userID);
				userToken = authenticateValue.then().extract().path("userToken");
				System.out.println("userToken:"+userToken);
				clientUserID = authenticateValue.then().extract().path("user.clientUserID");
				System.out.println("clientUserID:"+clientUserID);
				Log.endTestCase("End");
				
				
				Response fetchBookList_without_pagination = FetchBookList.fetchBookList_without_pagination(userToken,"45616452","IPAD");
				Validation.responseCodeValidation1(fetchBookList_without_pagination, HttpStatus.SC_OK);
				Validation.responseHeaderCodeValidation(fetchBookList_without_pagination, HttpStatus.SC_OK);
				Validation.responseTimeValidation(fetchBookList_without_pagination);
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "isbn");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "title");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "id");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "archiveDate");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "assetType");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "assignedOn");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "bookActive");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "bookCode");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "bookId");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "category");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "categoryIdList");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "categoryList");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "locale");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "collectionThumbnail");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "collectionType");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "formats");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "readingPercentage");
				Validation.responseKeyValidation_key(fetchBookList_without_pagination, "classID");
				//Validation.responseKeyValidation_key(jsonResponse, Title)
				bookID1 = fetchBookList_without_pagination.then().extract().path("bookList.book.id[0]");
				System.out.println("bookID_1: "+bookID1);
				bookID2 = fetchBookList_without_pagination.then().extract().path("bookList.book.id[1]");			
				System.out.println("bookID2: "+bookID2);
				bookID3 = fetchBookList_without_pagination.then().extract().path("bookList.book.id[2]");			
				System.out.println("bookID3: "+bookID3);
				bookID6 = fetchBookList_without_pagination.then().extract().path("bookList.book.id[6]");
				System.out.println("bookID6 :: "+bookID6);
				isbn = fetchBookList_without_pagination.then().extract().path("bookList.book.isbn[1]");
				System.out.println("isbn: "+isbn);
				type=fetchBookList_without_pagination.then().extract().path("bookList.book.type[0]");
				System.out.println("type: "+type);
				ebookID1 = fetchBookList_without_pagination.then().extract().path("bookList.book.ebookID[0]");
				System.out.println("ebookID: "+ebookID1);
				assetType = fetchBookList_without_pagination.then().extract().path("bookList.book.assetType[0]");
				System.out.println("assetType: "+assetType);
				category1 = fetchBookList_without_pagination.then().extract().path("bookList.book.category[0]");
				System.out.println("category1: "+category1);
				collectionName0 = fetchBookList_without_pagination.then().extract().path("bookList.book.collectionTitle[0]");
				System.out.println("collectionName0: "+collectionName0);
				catname = ExtractCategory.extractCategory(category1);
				System.out.println("catname: " +catname);
				/*forName = fetchBookList_without_pagination.then().extract().path("bookList.book.formats.name[0]");
				Log.info("$#@$#@#@#@##@#$!@#$%^#@#$%^ forName :: "+forName);*/
				archiveDate = fetchBookList_without_pagination.then().extract().path("bookList.book.archiveDate[0]");
				System.out.println("archiveDate:"+archiveDate);
				archiveDate6=fetchBookList_without_pagination.then().extract().path("bookList.book.archiveDate[6]");
				System.out.println("archiveDate:"+archiveDate);				
				categoryIdList0 = fetchBookList_without_pagination.then().extract().path("bookList.book.categoryIdList[0]");
				Log.info("categoryIdList0 : "+categoryIdList0);
				
		//IPAD		
				Response Refreshcategory_Refl=RefreshCategory.refreshCategory(categoryIdList0, userToken, "fs313", "IPAD");
				Validation.responseHeaderCodeValidation(Refreshcategory_Refl,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(Refreshcategory_Refl, HttpStatus.SC_OK);
				Validation.responseTimeValidation(Refreshcategory_Refl);
				responseMsg=Refreshcategory_Refl.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(Refreshcategory_Refl,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(Refreshcategory_Refl, "id");
				Validation.responseKeyValidation_key(Refreshcategory_Refl, "name");
				Validation.responseKeyValidation_key(Refreshcategory_Refl, "hash");
				Validation.responseKeyValidation_key(Refreshcategory_Refl, "bookIdList");	
				System.out.println("Refreshcategory_Refl : "+Refreshcategory_Refl);
				
				
				Response FetchBookList_Refl=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "IPAD");
				Validation.responseHeaderCodeValidation(FetchBookList_Refl,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_Refl, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_Refl);
				Validation.responseKeyValidation_key(FetchBookList_Refl, "154");
				title=FetchBookList_Refl.then().extract().path("bookList.book.title[0]");
				Log.info("title : "+title);
				category=FetchBookList_Refl.then().extract().path("bookList.book.category[0]");
				Log.info("category : "+category);
				//Validation.responseKcount(FetchBookList_Refl, category);
				//Validation.responseKcount1(FetchBookList_Refl, "08AUGDIS-1870");
				categoryList=FetchBookList_Refl.then().extract().path("bookList.book.categoryList[0]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_Refl.then().extract().path("bookList.book.categoryIdList[0]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_Refl : "+FetchBookList_Refl);
				Validation.responseKeyValidation_key(FetchBookList_Refl, "08AUGDIS-1870");
				categoryIdList1=FetchBookList_Refl.then().extract().path("bookList.book.categoryIdList[17]");
				
				Response RefreshcategoryFixed=RefreshCategory.refreshCategory(categoryIdList1, userToken, "fs313", "IPAD");
				Validation.responseHeaderCodeValidation(RefreshcategoryFixed,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(RefreshcategoryFixed, HttpStatus.SC_OK);
				Validation.responseTimeValidation(RefreshcategoryFixed);
				responseMsg=RefreshcategoryFixed.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(RefreshcategoryFixed,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(RefreshcategoryFixed, "id");
				Validation.responseKeyValidation_key(RefreshcategoryFixed, "name");
				Validation.responseKeyValidation_key(RefreshcategoryFixed, "hash");
				Validation.responseKeyValidation_key(RefreshcategoryFixed, "bookIdList");	
				System.out.println("RefreshCategory : "+RefreshcategoryFixed);
				
				Response FetchBookList_ver_fix=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "IPAD");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_fix,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_fix, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_fix);				
				Validation.responseKeyValidation_key(FetchBookList_ver_fix, "146");
				title=FetchBookList_ver_fix.then().extract().path("bookList.book.title[17]");
				Log.info("title : "+title);
				category=FetchBookList_ver_fix.then().extract().path("bookList.book.category[17]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_fix.then().extract().path("bookList.book.categoryList[17]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_fix.then().extract().path("bookList.book.categoryIdList[17]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_fix);
				Validation.responseKeyValidation_key(FetchBookList_ver_fix, "08AUGDIS-1870");
				categoryIdList2=FetchBookList_ver_fix.then().extract().path("bookList.book.categoryIdList[18]");
				
				Response RefreshcategoryVideo=RefreshCategory.refreshCategory(categoryIdList2, userToken, "fs313", "IPAD");
				Validation.responseHeaderCodeValidation(RefreshcategoryVideo,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(RefreshcategoryVideo, HttpStatus.SC_OK);
				Validation.responseTimeValidation(RefreshcategoryVideo);
				responseMsg=RefreshcategoryVideo.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(RefreshcategoryVideo,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(RefreshcategoryVideo, "id");
				Validation.responseKeyValidation_key(RefreshcategoryVideo, "name");
				Validation.responseKeyValidation_key(RefreshcategoryVideo, "hash");
				Validation.responseKeyValidation_key(RefreshcategoryVideo, "bookIdList");	
				System.out.println("RefreshCategory : "+RefreshcategoryVideo);
				
				Response FetchBookList_ver_video=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "IPAD");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_video,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_video, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_video);				
				Validation.responseKeyValidation_key(FetchBookList_ver_video, "206");
				title=FetchBookList_ver_video.then().extract().path("bookList.book.title[18]");
				Log.info("title : "+title);
				category=FetchBookList_ver_video.then().extract().path("bookList.book.category[18]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_video.then().extract().path("bookList.book.categoryList[18]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_video.then().extract().path("bookList.book.categoryIdList[18]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_video);
				Validation.responseKeyValidation_key(FetchBookList_ver_video, "08AUGDIS-1870");
				categoryIdList3=FetchBookList_ver_video.then().extract().path("bookList.book.categoryIdList[2]");
				
				Response Refreshcategory_Native=RefreshCategory.refreshCategory(categoryIdList3, userToken, "fs313", "IPAD");
				Validation.responseHeaderCodeValidation(Refreshcategory_Native,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(Refreshcategory_Native, HttpStatus.SC_OK);
				Validation.responseTimeValidation(Refreshcategory_Native);
				responseMsg =  Refreshcategory_Native.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(Refreshcategory_Native,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(Refreshcategory_Native, "id");
				Validation.responseKeyValidation_key(Refreshcategory_Native, "name");
				Validation.responseKeyValidation_key(Refreshcategory_Native, "hash");
				Validation.responseKeyValidation_key(Refreshcategory_Native, "bookIdList");	
				System.out.println("RefreshCategory : "+Refreshcategory_Native);
				
				Response FetchBookList_ver_Native=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "IPAD");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_Native,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_Native, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_Native);				
				Validation.responseKeyValidation_key(FetchBookList_ver_Native, "133");
				title=FetchBookList_ver_Native.then().extract().path("bookList.book.title[2]");
				Log.info("title : "+title);
				category=FetchBookList_ver_Native.then().extract().path("bookList.book.category[2]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_Native.then().extract().path("bookList.book.categoryList[2]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_Native.then().extract().path("bookList.book.categoryIdList[2]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_Native);
				Validation.responseKeyValidation_key(FetchBookList_ver_Native, "08AUGDIS-1870");
				categoryIdList4=FetchBookList_ver_Native.then().extract().path("bookList.book.categoryIdList[19]");
				
				Response Refreshcategory_Audio=RefreshCategory.refreshCategory(categoryIdList4, userToken, "fs313", "IPAD");
				Validation.responseHeaderCodeValidation(Refreshcategory_Audio,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(Refreshcategory_Audio, HttpStatus.SC_OK);
				Validation.responseTimeValidation(Refreshcategory_Audio);
				responseMsg =  Refreshcategory_Audio.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(Refreshcategory_Audio,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(Refreshcategory_Audio, "id");
				Validation.responseKeyValidation_key(Refreshcategory_Audio, "name");
				Validation.responseKeyValidation_key(Refreshcategory_Audio, "hash");
				Validation.responseKeyValidation_key(Refreshcategory_Audio, "bookIdList");	
				System.out.println("RefreshCategory : "+Refreshcategory_Audio);
				
				Response FetchBookList_ver_Audio=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "IPAD");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_Audio,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_Audio, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_Audio);				
				Validation.responseKeyValidation_key(FetchBookList_ver_Audio, "133");
				title=FetchBookList_ver_Audio.then().extract().path("bookList.book.title[19]");
				Log.info("title : "+title);
				category=FetchBookList_ver_Audio.then().extract().path("bookList.book.category[19]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_Audio.then().extract().path("bookList.book.categoryList[19]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_Audio.then().extract().path("bookList.book.categoryIdList[19]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_Audio);
				Validation.responseKeyValidation_key(FetchBookList_ver_Audio, "08AUGDIS-1870");
				//categoryIdList3=FetchBookList_ver_Audio.then().extract().path("bookList.book.categoryIdList[2]");
				
		//ANDROID		
				Response Refreshcategory_Refl1=RefreshCategory.refreshCategory(categoryIdList0, userToken, "fs313", "ANDROID");
				Validation.responseHeaderCodeValidation(Refreshcategory_Refl1,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(Refreshcategory_Refl1, HttpStatus.SC_OK);
				Validation.responseTimeValidation(Refreshcategory_Refl1);
				responseMsg=Refreshcategory_Refl1.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(Refreshcategory_Refl1,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(Refreshcategory_Refl1, "id");
				Validation.responseKeyValidation_key(Refreshcategory_Refl1, "name");
				Validation.responseKeyValidation_key(Refreshcategory_Refl1, "hash");
				Validation.responseKeyValidation_key(Refreshcategory_Refl1, "bookIdList");	
				System.out.println("Refreshcategory_Refl : "+Refreshcategory_Refl1);
				
				
				Response FetchBookList_Refl1=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "ANDROID");
				Validation.responseHeaderCodeValidation(FetchBookList_Refl1,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_Refl1, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_Refl1);
				Validation.responseKeyValidation_key(FetchBookList_Refl1, "154");
				title=FetchBookList_Refl1.then().extract().path("bookList.book.title[0]");
				Log.info("title : "+title);
				category=FetchBookList_Refl1.then().extract().path("bookList.book.category[0]");
				Log.info("category : "+category);
				categoryList=FetchBookList_Refl1.then().extract().path("bookList.book.categoryList[0]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_Refl1.then().extract().path("bookList.book.categoryIdList[0]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_Refl : "+FetchBookList_Refl1);
				Validation.responseKeyValidation_key(FetchBookList_Refl1, "08AUGDIS-1870");
				categoryIdList1=FetchBookList_Refl1.then().extract().path("bookList.book.categoryIdList[17]");
				
				Response RefreshcategoryFixed1=RefreshCategory.refreshCategory(categoryIdList1, userToken, "fs313", "ANDROID");
				Validation.responseHeaderCodeValidation(RefreshcategoryFixed1,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(RefreshcategoryFixed1, HttpStatus.SC_OK);
				Validation.responseTimeValidation(RefreshcategoryFixed1);
				responseMsg=RefreshcategoryFixed1.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(RefreshcategoryFixed1,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(RefreshcategoryFixed1, "id");
				Validation.responseKeyValidation_key(RefreshcategoryFixed1, "name");
				Validation.responseKeyValidation_key(RefreshcategoryFixed1, "hash");
				Validation.responseKeyValidation_key(RefreshcategoryFixed1, "bookIdList");	
				System.out.println("RefreshCategory : "+RefreshcategoryFixed1);
				
				Response FetchBookList_ver_fix1=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "ANDROID");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_fix1,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_fix1, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_fix1);				
				Validation.responseKeyValidation_key(FetchBookList_ver_fix1, "146");
				title=FetchBookList_ver_fix1.then().extract().path("bookList.book.title[17]");
				Log.info("title : "+title);
				category=FetchBookList_ver_fix1.then().extract().path("bookList.book.category[17]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_fix1.then().extract().path("bookList.book.categoryList[17]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_fix1.then().extract().path("bookList.book.categoryIdList[17]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_fix1);
				Validation.responseKeyValidation_key(FetchBookList_ver_fix1, "08AUGDIS-1870");
				categoryIdList2=FetchBookList_ver_fix1.then().extract().path("bookList.book.categoryIdList[18]");
				
				Response RefreshcategoryVideo1=RefreshCategory.refreshCategory(categoryIdList2, userToken, "fs313", "ANDROID");
				Validation.responseHeaderCodeValidation(RefreshcategoryVideo1,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(RefreshcategoryVideo1, HttpStatus.SC_OK);
				Validation.responseTimeValidation(RefreshcategoryVideo1);
				responseMsg=RefreshcategoryVideo1.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(RefreshcategoryVideo1,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(RefreshcategoryVideo1, "id");
				Validation.responseKeyValidation_key(RefreshcategoryVideo1, "name");
				Validation.responseKeyValidation_key(RefreshcategoryVideo1, "hash");
				Validation.responseKeyValidation_key(RefreshcategoryVideo1, "bookIdList");	
				System.out.println("RefreshCategory : "+RefreshcategoryVideo1);
				
				Response FetchBookList_ver_video1=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "ANDROID");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_video1,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_video1, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_video1);				
				Validation.responseKeyValidation_key(FetchBookList_ver_video1, "206");
				title=FetchBookList_ver_video1.then().extract().path("bookList.book.title[18]");
				Log.info("title : "+title);
				category=FetchBookList_ver_video1.then().extract().path("bookList.book.category[18]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_video1.then().extract().path("bookList.book.categoryList[18]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_video1.then().extract().path("bookList.book.categoryIdList[18]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_video1);
				Validation.responseKeyValidation_key(FetchBookList_ver_video1, "08AUGDIS-1870");
				categoryIdList3=FetchBookList_ver_video1.then().extract().path("bookList.book.categoryIdList[2]");
				
				Response Refreshcategory_Native1=RefreshCategory.refreshCategory(categoryIdList3, userToken, "fs313", "ANDROID");
				Validation.responseHeaderCodeValidation(Refreshcategory_Native1,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(Refreshcategory_Native1, HttpStatus.SC_OK);
				Validation.responseTimeValidation(Refreshcategory_Native1);
				responseMsg =  Refreshcategory_Native1.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(Refreshcategory_Native1,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(Refreshcategory_Native1, "id");
				Validation.responseKeyValidation_key(Refreshcategory_Native1, "name");
				Validation.responseKeyValidation_key(Refreshcategory_Native1, "hash");
				Validation.responseKeyValidation_key(Refreshcategory_Native1, "bookIdList");	
				System.out.println("RefreshCategory : "+Refreshcategory_Native1);
				
				Response FetchBookList_ver_Native1=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "ANDROID");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_Native1,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_Native1, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_Native1);				
				Validation.responseKeyValidation_key(FetchBookList_ver_Native1, "133");
				title=FetchBookList_ver_Native1.then().extract().path("bookList.book.title[2]");
				Log.info("title : "+title);
				category=FetchBookList_ver_Native1.then().extract().path("bookList.book.category[2]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_Native1.then().extract().path("bookList.book.categoryList[2]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_Native1.then().extract().path("bookList.book.categoryIdList[2]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_Native1);
				Validation.responseKeyValidation_key(FetchBookList_ver_Native1, "08AUGDIS-1870");
				categoryIdList4=FetchBookList_ver_Native1.then().extract().path("bookList.book.categoryIdList[19]");
				
				Response Refreshcategory_Audio1=RefreshCategory.refreshCategory(categoryIdList3, userToken, "fs313", "ANDROID");
				Validation.responseHeaderCodeValidation(Refreshcategory_Audio1,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(Refreshcategory_Audio1, HttpStatus.SC_OK);
				Validation.responseTimeValidation(Refreshcategory_Audio1);
				responseMsg =  Refreshcategory_Audio1.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(Refreshcategory_Audio1,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(Refreshcategory_Audio1, "id");
				Validation.responseKeyValidation_key(Refreshcategory_Audio1, "name");
				Validation.responseKeyValidation_key(Refreshcategory_Audio1, "hash");
				Validation.responseKeyValidation_key(Refreshcategory_Audio1, "bookIdList");	
				System.out.println("RefreshCategory : "+Refreshcategory_Audio1);
				
				Response FetchBookList_ver_Audio1=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "ANDROID");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_Audio1,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_Audio1, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_Audio1);				
				Validation.responseKeyValidation_key(FetchBookList_ver_Audio1, "133");
				title=FetchBookList_ver_Audio1.then().extract().path("bookList.book.title[19]");
				Log.info("title : "+title);
				category=FetchBookList_ver_Audio1.then().extract().path("bookList.book.category[19]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_Audio1.then().extract().path("bookList.book.categoryList[19]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_Audio1.then().extract().path("bookList.book.categoryIdList[19]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_Audio1);
				Validation.responseKeyValidation_key(FetchBookList_ver_Audio1, "08AUGDIS-1870");
				//categoryIdList3=FetchBookList_ver_Audio1.then().extract().path("bookList.book.categoryIdList[2]");
				
		//HTML5		
				Response Refreshcategory_Refl11=RefreshCategory.refreshCategory(categoryIdList0, userToken, "fs313", "HTML5");
				Validation.responseHeaderCodeValidation(Refreshcategory_Refl11,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(Refreshcategory_Refl11, HttpStatus.SC_OK);
				Validation.responseTimeValidation(Refreshcategory_Refl1);
				responseMsg=Refreshcategory_Refl11.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(Refreshcategory_Refl11,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(Refreshcategory_Refl11, "id");
				Validation.responseKeyValidation_key(Refreshcategory_Refl11, "name");
				Validation.responseKeyValidation_key(Refreshcategory_Refl11, "hash");
				Validation.responseKeyValidation_key(Refreshcategory_Refl11, "bookIdList");	
				System.out.println("Refreshcategory_Refl : "+Refreshcategory_Refl11);
				
				
				Response FetchBookList_Refl11=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "HTML5");
				Validation.responseHeaderCodeValidation(FetchBookList_Refl11,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_Refl11, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_Refl11);
				Validation.responseKeyValidation_key(FetchBookList_Refl11, "154");
				title=FetchBookList_Refl11.then().extract().path("bookList.book.title[0]");
				Log.info("title : "+title);
				category=FetchBookList_Refl11.then().extract().path("bookList.book.category[0]");
				Log.info("category : "+category);
				categoryList=FetchBookList_Refl11.then().extract().path("bookList.book.categoryList[0]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_Refl11.then().extract().path("bookList.book.categoryIdList[0]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_Refl : "+FetchBookList_Refl11);
				Validation.responseKeyValidation_key(FetchBookList_Refl11, "08AUGDIS-1870");
				categoryIdList1=FetchBookList_Refl11.then().extract().path("bookList.book.categoryIdList[17]");
				
				Response RefreshcategoryFixed11=RefreshCategory.refreshCategory(categoryIdList1, userToken, "fs313", "HTML5");
				Validation.responseHeaderCodeValidation(RefreshcategoryFixed11,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(RefreshcategoryFixed11, HttpStatus.SC_OK);
				Validation.responseTimeValidation(RefreshcategoryFixed11);
				responseMsg=RefreshcategoryFixed11.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(RefreshcategoryFixed11,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(RefreshcategoryFixed11, "id");
				Validation.responseKeyValidation_key(RefreshcategoryFixed11, "name");
				Validation.responseKeyValidation_key(RefreshcategoryFixed11, "hash");
				Validation.responseKeyValidation_key(RefreshcategoryFixed11, "bookIdList");	
				System.out.println("RefreshCategory : "+RefreshcategoryFixed11);
				
				Response FetchBookList_ver_fix11=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "HTML5");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_fix11,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_fix11, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_fix11);				
				Validation.responseKeyValidation_key(FetchBookList_ver_fix11, "146");
				title=FetchBookList_ver_fix11.then().extract().path("bookList.book.title[17]");
				Log.info("title : "+title);
				category=FetchBookList_ver_fix11.then().extract().path("bookList.book.category[17]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_fix11.then().extract().path("bookList.book.categoryList[17]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_fix11.then().extract().path("bookList.book.categoryIdList[17]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_fix11);
				Validation.responseKeyValidation_key(FetchBookList_ver_fix11, "08AUGDIS-1870");
				categoryIdList2=FetchBookList_ver_fix11.then().extract().path("bookList.book.categoryIdList[18]");
				
				Response RefreshcategoryVideo11=RefreshCategory.refreshCategory(categoryIdList2, userToken, "fs313", "HTML5");
				Validation.responseHeaderCodeValidation(RefreshcategoryVideo11,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(RefreshcategoryVideo11, HttpStatus.SC_OK);
				Validation.responseTimeValidation(RefreshcategoryVideo11);
				responseMsg=RefreshcategoryVideo11.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(RefreshcategoryVideo11,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(RefreshcategoryVideo11, "id");
				Validation.responseKeyValidation_key(RefreshcategoryVideo11, "name");
				Validation.responseKeyValidation_key(RefreshcategoryVideo11, "hash");
				Validation.responseKeyValidation_key(RefreshcategoryVideo11, "bookIdList");	
				System.out.println("RefreshCategory : "+RefreshcategoryVideo11);
				
				Response FetchBookList_ver_video11=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "HTML5");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_video11,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_video11, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_video11);				
				Validation.responseKeyValidation_key(FetchBookList_ver_video11, "206");
				title=FetchBookList_ver_video11.then().extract().path("bookList.book.title[18]");
				Log.info("title : "+title);
				category=FetchBookList_ver_video11.then().extract().path("bookList.book.category[18]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_video11.then().extract().path("bookList.book.categoryList[18]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_video11.then().extract().path("bookList.book.categoryIdList[18]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_video11);
				Validation.responseKeyValidation_key(FetchBookList_ver_video11, "08AUGDIS-1870");
				categoryIdList3=FetchBookList_ver_video11.then().extract().path("bookList.book.categoryIdList[2]");
				
				Response Refreshcategory_Native12=RefreshCategory.refreshCategory(categoryIdList3, userToken, "fs313", "HTML5");
				Validation.responseHeaderCodeValidation(Refreshcategory_Native12,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(Refreshcategory_Native12, HttpStatus.SC_OK);
				Validation.responseTimeValidation(Refreshcategory_Native12);
				responseMsg =  Refreshcategory_Native12.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(Refreshcategory_Native12,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(Refreshcategory_Native12, "id");
				Validation.responseKeyValidation_key(Refreshcategory_Native12, "name");
				Validation.responseKeyValidation_key(Refreshcategory_Native12, "hash");
				Validation.responseKeyValidation_key(Refreshcategory_Native12, "bookIdList");	
				System.out.println("RefreshCategory : "+Refreshcategory_Native12);
				
				Response FetchBookList_ver_Native11=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "HTML5");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_Native11,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_Native11, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_Native11);				
				Validation.responseKeyValidation_key(FetchBookList_ver_Native11, "133");
				title=FetchBookList_ver_Native11.then().extract().path("bookList.book.title[2]");
				Log.info("title : "+title);
				category=FetchBookList_ver_Native11.then().extract().path("bookList.book.category[2]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_Native11.then().extract().path("bookList.book.categoryList[2]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_Native11.then().extract().path("bookList.book.categoryIdList[2]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_Native11);
				Validation.responseKeyValidation_key(FetchBookList_ver_Native11, "08AUGDIS-1870");
				categoryIdList3=FetchBookList_ver_Native11.then().extract().path("bookList.book.categoryIdList[19]");
				
				
				Response Refreshcategory_Audio12=RefreshCategory.refreshCategory(categoryIdList3, userToken, "fs313", "HTML5");
				Validation.responseHeaderCodeValidation(Refreshcategory_Audio12,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(Refreshcategory_Audio12, HttpStatus.SC_OK);
				Validation.responseTimeValidation(Refreshcategory_Audio12);
				responseMsg =  Refreshcategory_Audio12.then().extract().path("responseMsg");
				Validation.responseKeyAndValue(Refreshcategory_Audio12,"responseMsg","SUCCESS");
				Validation.responseKeyValidation_key(Refreshcategory_Audio12, "id");
				Validation.responseKeyValidation_key(Refreshcategory_Audio12, "name");
				Validation.responseKeyValidation_key(Refreshcategory_Audio12, "hash");
				Validation.responseKeyValidation_key(Refreshcategory_Audio12, "bookIdList");	
				System.out.println("RefreshCategory : "+Refreshcategory_Audio12);
				
				Response FetchBookList_ver_Audio11=FetchBookList.fetchBookList_without_pagination(userToken, "ewe3242", "HTML5");
				Validation.responseHeaderCodeValidation(FetchBookList_ver_Audio11,HttpStatus.SC_OK);
				Validation.responseCodeValidation1(FetchBookList_ver_Audio11, HttpStatus.SC_OK);
				Validation.responseTimeValidation(FetchBookList_ver_Audio11);				
				Validation.responseKeyValidation_key(FetchBookList_ver_Audio11, "133");
				title=FetchBookList_ver_Audio11.then().extract().path("bookList.book.title[19]");
				Log.info("title : "+title);
				category=FetchBookList_ver_Audio11.then().extract().path("bookList.book.category[19]");
				Log.info("category : "+category);
				categoryList=FetchBookList_ver_Audio11.then().extract().path("bookList.book.categoryList[19]");
				Log.info("categoryList : "+categoryList);
				categoryIdList=FetchBookList_ver_Audio11.then().extract().path("bookList.book.categoryIdList[19]");
				Log.info("categoryIdList : "+categoryIdList);
				System.out.println("FetchBookList_ver : "+FetchBookList_ver_Audio11);
				Validation.responseKeyValidation_key(FetchBookList_ver_Audio11, "08AUGDIS-1870");
				//ArrayList<String> category[]=FetchBookList_ver_Audio11.then().extract().path("bookList.book.category");
				//Object category = FetchBookList_ver_Audio11.then().extract().path("bookList.book.category");
				List<String> category = FetchBookList_ver_Audio11.then().extract().path("bookList.book.category");
				//boolean count=category.contains("08AUGDIS-1870");
				Log.info("category AS WHOLE LIST  : "+category);
				Log.info("category SIZE IS : "+category.size());
		//Validation.responseKcount_Str(category, "08AUGDIS-1870");
				//categoryIdList3=FetchBookList_ver_Audio11.then().extract().path("bookList.book.categoryIdList[19]");
				
			}
		}catch (Exception exp) 
		{
			System.out.println(exp.getMessage());
			System.out.println(exp.getCause());
			exp.printStackTrace();
		}
	}
}
